/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package baraaAlosaily.data.structure.and.algorithem.mosh;

public class App {
    public static void main(String[] args) {
        Graph graph=new Graph();
        graph.addNode("red");
        graph.addNode("blue");
        graph.addNode("gray");
        graph.addNode("black");
        graph.addNode("white");
        graph.addEdge("red","blue");
        graph.addEdge("gray","black");
        graph.addEdge("white","red");
        graph.addEdge("red","gray");
        graph.addEdge("blue","gray");
        graph.addEdge("white","blue");
        graph.addEdge("white","gray");
        graph.addEdge("white","black");

//        graph.removeNode("white");
//
//        graph.removeEdge("red","gray");
//        graph.removeEdge("white","black");
        graph.print();

        graph.traverseDepthFirstRec("white");
        System.out.println("********************");
        graph.traverseDepthFirst("white");
        System.out.println("********************");
        graph.traverseBreadthFirst("white");


    }
}
